name: 機能要望
description: 新機能や改善提案を記録します
title: "[Feature] 要望の要約"
labels: [enhancement]
assignees: []
body:
  - type: textarea
    id: background
    attributes:
      label: 背景 / 課題
      description: どんな課題を解決したいですか？ユーザー価値や文脈も含めてください。
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: 提案内容
      description: 具体的な案（UI/操作/技術アプローチ）を記載してください。
      placeholder: 例）`R`キーで車両を初期位置にリセットする
    validations:
      required: true

  - type: textarea
    id: acceptance
    attributes:
      label: 受け入れ基準 (Acceptance Criteria)
      description: 完了判定のための条件を箇条書きで記載してください。
      placeholder: |
        - `R`キーで毎回確実に初期位置に戻る
        - デバッグUIに「リセット」ボタンがある
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: 代替案/関連情報
      description: 他の案や参考リンクがあれば記載してください。
    validations:
      required: false

