name: タスク
description: 開発・保守・ドキュメントなどの一般タスク
title: "[Task] タスクの要約"
labels: [task]
assignees: []
body:
  - type: textarea
    id: summary
    attributes:
      label: 概要
      placeholder: 例）`npm run dev` を追加してポートを統一
    validations:
      required: true

  - type: textarea
    id: goal
    attributes:
      label: 目的/背景
      placeholder: なぜこのタスクが必要か？期待する効果は？
    validations:
      required: true

  - type: textarea
    id: scope
    attributes:
      label: スコープ
      description: 含むこと/含まないことを明確にしてください。
      placeholder: |
        含む: package.json に dev スクリプト追加、README更新
        含まない: Vite等への全面移行
    validations:
      required: false

  - type: textarea
    id: acceptance
    attributes:
      label: 完了条件 (Acceptance Criteria)
      placeholder: 箇条書きで記載
    validations:
      required: true

  - type: input
    id: estimate
    attributes:
      label: 見積もり
      placeholder: 1h / 0.5d など
    validations:
      required: false

